In [1]:
import tensorflow as tf
#sess = tf.InteractiveSession()
tf.__version__

'1.1.0'

<h1>  Constants</h1>

In [2]:
hello_constant = tf.constant("Hello World!")
print(hello_constant)

Tensor("Const:0", shape=(), dtype=string)


In [4]:
# Run the tf.constant operation in the session
sess =  tf.Session() 
output = sess.run(hello_constant)
print(output)

b'Hello World!'


In [5]:
a = tf.constant(10, name="const3")
b = tf.constant(20, name="const4")
add = tf.add(a, b)

with tf.Session() as sess:
    sum = sess.run(add)
    print(sum)
    

30


<img src="https://www.tensorflow.org/images/getting_started_add.png"/>

In [6]:
c = tf.constant([[1, 2, 3], [4, 5, 6]])
with tf.Session() as sess:
    product = sess.run(a*c)
    print(product)

[[10 20 30]
 [40 50 60]]


In [ ]:
# Do 10/2 - 1 = 4 
x = tf.constant(10)
y = tf.constant(2)
z = tf.subtract(tf.divide(x, y), tf.cast(tf.constant(1), tf.float64))

with tf.Session() as sess:
    output = sess.run(z)
    print(output)

<h1>  Placeholders </h1>

In [10]:
x = tf.placeholder(tf.string)
with tf.Session() as sess:
    output = sess.run(x, feed_dict={x: 'Hello World'})
    print(output)

Hello World


In [13]:
x = tf.placeholder(tf.string)
y = tf.placeholder(tf.int32)
z = tf.placeholder(tf.float32)

with tf.Session() as sess:
    x_value = sess.run(x, feed_dict={x: 'Test String'})
    y_value = sess.run(y, feed_dict={y: 20})
    z_value = sess.run(z, feed_dict={z: 45.67})
    print("x=",x_value, ", y=",y_value, ", z=",z_value)
    
    x_value, y_value, z_value = sess.run([x, y, z], feed_dict={x: 'Test String', y: 20, z: 45.67})
    print("x=",x_value, ", y=",y_value, ", z=",z_value)

    print(sess.run(a + y , feed_dict={x: 'Test String', y: 20, z: 45.67}))

x= Test String , y= 20 , z= 45.66999816894531
x= Test String , y= 20 , z= 45.66999816894531
30


In [14]:
a = tf.placeholder(tf.float32)
b = tf.placeholder(tf.float32)
adder_node = a + b  # + provides a shortcut for tf.add(a, b)

sess = tf.Session()
print(sess.run(adder_node, {a: 3, b: 4.5}))
print(sess.run(adder_node, {a: [1, 3], b: [2, 4]}))

add_and_triple = adder_node * 3.
print(sess.run(add_and_triple, {a: 3, b: 4.5}))


7.5
[ 3.  7.]
22.5


<img src="https://www.tensorflow.org/images/getting_started_adder.png" />
<img src="https://www.tensorflow.org/images/getting_started_triple.png" />

<h1> Variables </h1>

In [15]:
# Variables
W = tf.Variable([.3], dtype=tf.float32)
b = tf.Variable([-.3], dtype=tf.float32)
x = tf.placeholder(tf.float32)

z = W*x + b

In [17]:
# To initialize all the variables in a TensorFlow program, you must explicitly call a special operation as follows:
init = tf.global_variables_initializer()
sess.run(init)

In [18]:
print(sess.run(z, {x: [1, 2, 3, 4]}))

[ 0.          0.30000001  0.60000002  0.90000004]


In [19]:
x = tf.placeholder(tf.float32)
avg = tf.reduce_mean(x)
sess.run(avg, feed_dict={x:[10,20,30]})

20.0